# Generated by Django 2.0.6 on 2018-08-17 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('stucls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.cls')),
            ],
            options={
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='useraccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('pwd', models.CharField(max_length=10)),
                ('emil', models.EmailField(max_length=20)),
            ],
        ),
    ]
