# Generated by Django 2.0.6 on 2018-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('cls', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书籍'},
        ),
    ]
