# Generated by Django 2.0.6 on 2018-08-14 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180814_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cls',
            options={'verbose_name_plural': '班级'},
        ),
    ]
