# Generated by Django 2.0.6 on 2018-08-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_public'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
